version: "3"

services:
  marketplace:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    ports:
      - "4040:4040"
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgresql-master
      - postgresql-slave

    networks:
      - postgres

  postgresql-master:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=marketplace
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - postgres
  postgresql-slave:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432'
    volumes:
      - 'postgresql_slave_data:/bitnami/postgresql'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - postgres
networks:
  postgres:
    driver: bridge

volumes:
  postgresql_master_data:
    driver: local
  postgresql_slave_data:
    driver: local

